name: PHP tests

on:
  push:
    branches: [master]
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        php:
          - 7.4
          - 8.0

    name: PHP ${{ matrix.php }}

    steps:
      - name: Code checkout
        uses: actions/checkout@v2

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.composer/cache/files
          key: data-mapper-php${{ matrix.php }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist --no-suggest

      - name: Run CodeSniffer
        run: ./vendor/bin/phpcs -p

      - name: Run PHPStan
        run: ./vendor/bin/phpstan analyse --no-progress

      - name: Run PHPUnit
        run: ./vendor/bin/phpunit
